#
#
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
#
#
# Name of website
title: Gestion de accidentes

# Short description of your site
description: Gestion de accientes con gvSIG desktop basada en la informacion de ARENA2 de la DGT.

theme: jekyll-theme-hacker

# Exclude these files from production site
exclude:
  - all.md
  - arena2.odt
  
