
# Name of website
title: Gestion de accidentes

# Short description of your site
description: Cestion de accientes con gvSIG desktop basada en la informacion de ARENA2 de la DGT.

theme: jekyll-theme-slate
